#ifndef TALCS_FUTUREAUDIOSOURCECLIPSERIESMANIPULATOR_H
#define TALCS_FUTUREAUDIOSOURCECLIPSERIESMANIPULATOR_H

namespace talcs {

    class FutureAudioSourceClipSeriesManipulator {};

}

#endif // TALCS_FUTUREAUDIOSOURCECLIPSERIESMANIPULATOR_H
