#ifndef TALCS_FUTUREAUDIOSOURCECLIPSERIESMANIPULATOR_H
#define TALCS_FUTUREAUDIOSOURCECLIPSERIESMANIPULATOR_H

namespace talcs {

    class FutureAudioSourceClipSeriesManipulator {};

} // talcs

#endif // TALCS_FUTUREAUDIOSOURCECLIPSERIESMANIPULATOR_H
