var annotated_dup =
[
    [ "talcs", null, [
      [ "ASIOAudioDevice", "classtalcs_1_1_a_s_i_o_audio_device.html", "classtalcs_1_1_a_s_i_o_audio_device" ],
      [ "ASIOAudioDriver", "classtalcs_1_1_a_s_i_o_audio_driver.html", "classtalcs_1_1_a_s_i_o_audio_driver" ],
      [ "AudioBuffer", "classtalcs_1_1_audio_buffer.html", "classtalcs_1_1_audio_buffer" ],
      [ "AudioClipBase", "structtalcs_1_1_audio_clip_base.html", "structtalcs_1_1_audio_clip_base" ],
      [ "AudioClipSeriesBase", "classtalcs_1_1_audio_clip_series_base.html", "classtalcs_1_1_audio_clip_series_base" ],
      [ "AudioDataWrapper", "classtalcs_1_1_audio_data_wrapper.html", "classtalcs_1_1_audio_data_wrapper" ],
      [ "AudioDevice", "classtalcs_1_1_audio_device.html", "classtalcs_1_1_audio_device" ],
      [ "AudioDeviceCallback", "classtalcs_1_1_audio_device_callback.html", "classtalcs_1_1_audio_device_callback" ],
      [ "AudioDriver", "classtalcs_1_1_audio_driver.html", "classtalcs_1_1_audio_driver" ],
      [ "AudioDriverManager", "classtalcs_1_1_audio_driver_manager.html", "classtalcs_1_1_audio_driver_manager" ],
      [ "AudioFormatInputSource", "classtalcs_1_1_audio_format_input_source.html", "classtalcs_1_1_audio_format_input_source" ],
      [ "AudioFormatIO", "classtalcs_1_1_audio_format_i_o.html", "classtalcs_1_1_audio_format_i_o" ],
      [ "AudioSampleConverter", "classtalcs_1_1_audio_sample_converter.html", null ],
      [ "AudioSource", "classtalcs_1_1_audio_source.html", "classtalcs_1_1_audio_source" ],
      [ "AudioSourceClipSeries", "classtalcs_1_1_audio_source_clip_series.html", "classtalcs_1_1_audio_source_clip_series" ],
      [ "AudioSourcePlayback", "classtalcs_1_1_audio_source_playback.html", "classtalcs_1_1_audio_source_playback" ],
      [ "AudioSourceReadData", "classtalcs_1_1_audio_source_read_data.html", "classtalcs_1_1_audio_source_read_data" ],
      [ "AudioStreamBase", "classtalcs_1_1_audio_stream_base.html", "classtalcs_1_1_audio_stream_base" ],
      [ "ErrorStringProvider", "classtalcs_1_1_error_string_provider.html", "classtalcs_1_1_error_string_provider" ],
      [ "IAudioSampleContainer", "classtalcs_1_1_i_audio_sample_container.html", "classtalcs_1_1_i_audio_sample_container" ],
      [ "IAudioSampleProvider", "classtalcs_1_1_i_audio_sample_provider.html", "classtalcs_1_1_i_audio_sample_provider" ],
      [ "IMixer", "structtalcs_1_1_i_mixer.html", "structtalcs_1_1_i_mixer" ],
      [ "InterleavedAudioDataWrapper", "classtalcs_1_1_interleaved_audio_data_wrapper.html", "classtalcs_1_1_interleaved_audio_data_wrapper" ],
      [ "MemoryAudioSource", "classtalcs_1_1_memory_audio_source.html", "classtalcs_1_1_memory_audio_source" ],
      [ "MixerAudioSource", "classtalcs_1_1_mixer_audio_source.html", "classtalcs_1_1_mixer_audio_source" ],
      [ "NameProvider", "classtalcs_1_1_name_provider.html", "classtalcs_1_1_name_provider" ],
      [ "PositionableAudioSource", "classtalcs_1_1_positionable_audio_source.html", "classtalcs_1_1_positionable_audio_source" ],
      [ "PositionableMixerAudioSource", "classtalcs_1_1_positionable_mixer_audio_source.html", "classtalcs_1_1_positionable_mixer_audio_source" ],
      [ "SDLAudioDevice", "classtalcs_1_1_s_d_l_audio_device.html", "classtalcs_1_1_s_d_l_audio_device" ],
      [ "SDLAudioDriver", "classtalcs_1_1_s_d_l_audio_driver.html", "classtalcs_1_1_s_d_l_audio_driver" ],
      [ "SineWaveAudioSource", "classtalcs_1_1_sine_wave_audio_source.html", "classtalcs_1_1_sine_wave_audio_source" ],
      [ "TransportAudioSource", "classtalcs_1_1_transport_audio_source.html", "classtalcs_1_1_transport_audio_source" ],
      [ "TransportAudioSourceWriter", "classtalcs_1_1_transport_audio_source_writer.html", "classtalcs_1_1_transport_audio_source_writer" ]
    ] ]
];