name: Coverity Scan

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Initialize Building Environment
        uses: ./.github/actions/init-build
        with:
          os: ubuntu-latest
          qt-version: '5.15.2'

      - name: Load TALCS CMake project
        shell: pwsh
        run: |
          cmake -B build -G Ninja `
            -DCMAKE_BUILD_TYPE=RelWithDebInfo `
            -DCMAKE_TOOLCHAIN_FILE="${{ env.VCPKG_ROOT_DIR }}/scripts/buildsystems/vcpkg.cmake" `
            -DTALCS_BUILD_TESTS:BOOL=ON `
            -DTALCS_ENABLE_ASIO:BOOL=ON `
            -DTALCS_REMOTE:BOOL=ON `
            -DTALCS_DSPX:BOOL=ON `
            -DTALCS_GUI:BOOL=ON `
            -DTALCS_ASIOSDK_DIR=${{ env.ASIOSDK_DIR }}
          
      - name: Build TALCS with Coverity Scan
        uses: vapier/coverity-scan-action@v1
        with:
          command: cmake --build build
          email: crs_16423@outlook.com
          token: ${{ secrets.COVERITY_SCAN_TOKEN }}